# Kubernetes and Google Cloud

sudo: required
service:
  - docker
before_install:
  # Travis CI encrypted service account file
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download and install Google Cloud SDK
  - source $HOME/google-cloud-sdk/path.bash.inc # look in default install directory and source the file
  - gcloud components update kubectl # install and update kubectl
  - gcloud auth activate-service-account --key-file service-account.json # Auth
