# Docker and AWS Elatic Beanstalk
sudo: required
services:
  - docker

# build test image
before_install:
  - docker build -t hakimixx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hakimixx/react-test npm test

# build PROD images
after_success:
  - docker build -t hakimixx/docker-infra-client ./client
  - docker build -t hakimixx/docker-infra-nginx ./nginx
  - docker build -t hakimixx/docker-infra-server ./server
  - docker build -t hakimixx/docker-infra-worker ./worker
  # Login to Docker Hub (using Travis CI environment variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to Docker Hub
  - docker push hakimixx/docker-infra-client
  - docker push hakimixx/docker-infra-nginx
  - docker push hakimixx/docker-infra-server
  - docker push hakimixx/docker-infra-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: docker-infrastructure
  env: docker-infrastructure-env
  bucket_name: elasticbeanstalk-eu-west-1-305477839034
  bucket_path: docker-infrastructure
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY # stored as env in travis
  secret_access_key:
    secure: $AWS_SECRET_KEY # stored as env in travis
