apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD # required by postgres
              valueFrom:
                secretKeyRef:
                  name: pgpassword # name of secret
                  key: PGPASSWORD # secret key (secret is stored as key-value-pair)
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # postgres default storage location
              subPath: postgres # any data stored in the postgres default path, will be stored in a /postgres folder in the PVC
